"""Initial migration

Revision ID: 37da294d5cbf
Revises: 
Create Date: 2025-04-17 22:41:48.549475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da294d5cbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cena_por_una_sonrisa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_apellido', sa.String(length=120), nullable=False),
    sa.Column('direccion_pais', sa.String(length=120), nullable=True),
    sa.Column('cena_asistira', sa.String(length=50), nullable=True),
    sa.Column('tipo_comida', sa.String(length=50), nullable=True),
    sa.Column('cantidad_invitados', sa.Integer(), nullable=True),
    sa.Column('nombres_acompanantes', sa.Text(), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('codigo_unico', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_unico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cena_por_una_sonrisa')
    # ### end Alembic commands ###
