"""relacionar formulario con pais y dividir direccion_pais

Revision ID: 76f9dafd96e8
Revises: 37da294d5cbf
Create Date: 2025-04-17 23:12:01.085435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f9dafd96e8'
down_revision = '37da294d5cbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=120), nullable=True))
        batch_op.drop_column('direccion_pais')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_pais', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
