"""Add cena_name field

Revision ID: 90adc5edb459
Revises: 
Create Date: 2025-04-18 13:42:42.079873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90adc5edb459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cena_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.drop_column('cena_name')

    # ### end Alembic commands ###
