"""Separa el campo nombre_apellido en nombre y apellido

Revision ID: a7e2be144a0f
Revises: bb9f00c9a923
Create Date: 2025-04-17 23:39:16.589628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e2be144a0f'
down_revision = 'bb9f00c9a923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=60), nullable=False))
        batch_op.drop_column('nombre_apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
