"""pais y direccion

Revision ID: bb9f00c9a923
Revises: 76f9dafd96e8
Create Date: 2025-04-17 23:22:11.731453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9f00c9a923'
down_revision = '76f9dafd96e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'countries', ['pais_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cena_por_una_sonrisa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pais_id')

    # ### end Alembic commands ###
